# Generated by Django 3.2.7 on 2021-11-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cominfo', '0002_auto_20211117_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='author',
            new_name='ceo',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='category_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='youtube_vid',
            new_name='website',
        ),
    ]
